version: "3.2"
services:

  redis:
    image: "redis:alpine"

    command: redis-server --requirepass sOmE_sEcUrE_pAsS

    ports:
      - "6379:6379"

    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

  wiremock:
    image: rodolpheche/wiremock:2.25.1-alpine
    volumes:
      - ./wiremock/mappings/:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--verbose", "--global-response-templating", "--no-request-journal" ]
    ports:
      - "9090:8080"